// Copy for the offer screens (T3). Registered with the shared t() dictionary
// at module scope, so French can be added later with the same keys.
// Import this module (for its side effect) from every offer component.

import { extendStrings } from "@/lib/app/strings"

extendStrings("en", {
  // list
  "o.list.needReply": "{count} offers need a reply",
  "o.list.needReply_one": "1 offer needs a reply",
  "o.list.soonest": "Soonest reply by {date}",
  "o.list.allAnswered": "All offers answered",
  "o.list.answered": "Answered",
  "o.list.noBidding": "No bidding. Each offer went only to your shop.",
  "o.list.total": "{value} of work offered · {hours} hrs/wk for the open offers",
  "o.list.totalNoneOpen": "{value} of work offered · no offers waiting for an answer",
  "o.list.none": "No offers for this shop",
  "o.list.noneBody": "Northgate matched its parts list to shops, but none of the jobs went to this shop.",
  "o.list.error": "Could not load offers",
  "o.list.retry": "Try again",
  "o.list.valueLabel": "Total value",
  "o.list.hoursWeek": "{hours} hrs/wk",
  "o.chip.replyBy": "Reply by {date}",
  "o.chip.new": "New",
  "o.chip.newTitle": "Offered after Northgate funded training at your shop",
  "o.chip.willSend": "Will send",
  "o.replyBy.assumption": "The defence company sets the reply-by date; the demo uses 5 business days after matching.",

  // card
  "o.card.notFound": "This job isn't offered to your shop",
  "o.card.notFoundBody": "It may have gone to another shop, or the link is from another shop.",
  "o.card.backToOffers": "Back to offers",
  "o.card.part": "Part {part}",
  "o.card.qty": "{qty} parts (fleet lifetime)",
  "o.card.unitPrice": "{price} each · unit price as given",
  "o.card.totalValue": "Total value",
  "o.card.hoursWeek": "Hours per week",
  "o.card.hoursUnit": "hrs/wk",
  "o.card.distance": "{km} from Northgate's site",
  "o.card.controlled": "Controlled goods",
  "o.card.why": "Why you",
  "o.card.canWe": "Can we do it?",
  "o.card.canWe.pass": "Everything checks out",
  "o.card.canWe.warn": "Check the flagged items",
  "o.card.canWe.fail": "Something doesn't fit",
  "o.card.noJobData": "Job details are still loading; the checklist appears once they arrive.",
  "o.card.noBidding": "No bidding.",
  "o.card.onlyYou": "{prime} offered this job only to you.",
  "o.card.credit": "{prime} earns {credit} Canada work credit (ITB) if you accept ({mult}).",
  "o.card.creditAccepted": "{prime} earns {credit} Canada work credit (ITB) because you accepted ({mult}).",
  "o.card.creditSimulated": "{prime} earns {credit} Canada work credit (ITB): the demo simulator accepted for this shop ({mult}).",
  "o.card.mult.sme": "small business: counts double",
  "o.card.mult.plain": "counts {mult}×",
  "o.card.itbGloss": "Credit isn't cash. It's how the government counts Northgate's Canadian business toward what it owes. Small-business work counts double.",
  "o.card.training": "Welders in training: start after they qualify.",
  "o.card.trainingBody": "Northgate is paying to train your welders for {cert}. This job needs it, so work starts once they pass.",
  "o.card.canWe.show": "Show the {count} checks",
  "o.card.canWe.hide": "Hide the checks",
  "o.card.payment": "Payment terms: set by Northgate. Not in demo data.",
  "o.card.paymentNote": "Shieldworks does not invent payment terms; the defence company sets them in its purchase order.",
  "o.card.drawings.controlled":
    "Drawings are never stored in Shieldworks. After you accept, Northgate releases the technical data package through its own controlled channel once your security clearance (Controlled Goods) is confirmed.",
  "o.card.drawings.plain": "Drawings are released by Northgate after acceptance, outside Shieldworks.",
  "o.card.share": "Send to estimator",
  "o.card.shareTitle": "Northgate offer {job}",
  "o.card.shareText":
    "Northgate offer {job} ({part}): {desc}. {qty} parts (fleet lifetime), {value} total, {hours} h/wk. Reply in Shieldworks by {date}. Drawings are released by Northgate after acceptance, outside Shieldworks.",
  "o.card.shareTextNoDate":
    "Northgate offer {job} ({part}): {desc}. {qty} parts (fleet lifetime), {value} total, {hours} h/wk. Reply in Shieldworks. Drawings are released by Northgate after acceptance, outside Shieldworks.",
  "o.card.linkCopied": "Link copied",
  "o.card.linkCopiedBody": "Paste it to your estimator. It carries no drawings or dimensions.",
  "o.card.shareFailed": "Could not share",

  // decision bar / status
  "o.bar.label": "Your answer",
  "o.bar.accepting": "Sending…",
  "o.status.accepted": "Accepted {date}",
  "o.status.acceptedNoDate": "Accepted",
  "o.status.declined": "Declined: {reason}",
  "o.status.declinedNoReason": "Declined",
  "o.status.question": "Question sent: {question}",
  "o.status.questionBody": "Northgate replies by email. You can still accept or decline.",
  "o.status.questionReplied": "You can still accept or decline.",
  "o.status.acceptedSim": "Accepted by the demo simulator {date}",
  "o.status.acceptedNoDateSim": "Accepted by the demo simulator",
  "o.status.declinedSim": "Declined by the demo simulator: {reason}",
  "o.status.declinedNoReasonSim": "Declined by the demo simulator",
  "o.status.questionSim": "Question sent by the demo simulator: {question}",
  "o.status.simBody": "A scripted demo answer, not this shop's own. You can change it.",
  "o.reply.title": "{prime} replied",
  "o.reply.demo": "Recorded on this device (demo)",
  "o.status.keep": "Keep my answer",
  "o.toast.accepted": "Accepted",
  "o.toast.acceptedBody": "{prime} sees it now. Undo within 10 seconds.",
  "o.toast.declined": "Declined: {reason}",
  "o.toast.declinedBody": "{prime} sees your reason.",
  "o.toast.question": "Question sent: {question}",
  "o.toast.questionBody": "{prime} replies by email.",
  "o.toast.undone": "Answer withdrawn",
  "o.toast.undoneBody": "{job} is open again.",

  // decline sheet
  "o.decline.title": "Decline {job}?",
  "o.decline.body": "Pick a reason. {prime} sees it right away.",
  "o.decline.reasons": "Reason",
  "o.decline.note": "Note (optional)",
  "o.decline.noteHelp": "No drawings, dimensions or technical data.",
  "o.decline.count": "{n} / 280",
  "o.decline.submit": "Send decline",
  "o.decline.pick": "Pick a reason first",

  // ask sheet
  "o.ask.title": "Ask Northgate about {job}",
  "o.ask.body": "Pick a question. Northgate replies by email. There is no chat, so no technical data ends up in Shieldworks.",
  "o.ask.questions": "Question",
  "o.ask.submit": "Send question",
  "o.ask.pick": "Pick a question first",

  // read-only view for the defence company (?from=prime)
  "o.prime.readOnly": "You're viewing {shop}'s offer. Only the shop can answer it.",
  "o.prime.onlyYou": "You offered this job only to {shop}.",
  "o.prime.credit": "You earn {credit} Canada work credit (ITB) if {shop} accepts ({mult}).",
  "o.prime.creditAccepted": "You earn {credit} Canada work credit (ITB) because {shop} accepted ({mult}).",
  "o.prime.creditSimulated": "You earn {credit} Canada work credit (ITB): the demo simulator accepted for {shop} ({mult}).",
  "o.prime.itbGloss": "Credit isn't cash. It's how the government counts your Canadian business toward what you owe. Small-business work counts double.",
  "o.prime.why": "Why {shop}",
  "o.prime.training": "Welders in training: work starts after they qualify.",
  "o.prime.trainingBody": "You are paying to train {shop}'s welders for {cert}. This job needs it, so work starts once they pass.",
  "o.prime.payment": "Payment terms: set in your purchase order. Not in demo data.",
  "o.prime.drawings.controlled":
    "Drawings are never stored in Shieldworks. After {shop} accepts, you release the technical data package through your own controlled channel once its security clearance (Controlled Goods) is confirmed.",
  "o.prime.drawings.plain": "You release drawings after {shop} accepts, outside Shieldworks.",
  "o.prime.status.label": "{shop}'s answer",
  "o.prime.status.accepted": "Accepted by {shop} · {date}",
  "o.prime.status.acceptedNoDate": "Accepted by {shop}",
  "o.prime.status.declined": "Declined by {shop}: {reason}",
  "o.prime.status.declinedNoReason": "Declined by {shop}",
  "o.prime.status.question": "{shop} asked: {question}",
  "o.prime.status.open": "Waiting for {shop}'s answer",
  "o.prime.status.sim": "Answered by the demo simulator for {shop}.",
  "o.prime.replied": "You replied: “{text}”",
  "o.prime.replyCta": "Reply on your To do screen",
  "o.prime.back": "Back to your To do screen",

  "o.sheet.cancel": "Cancel",
  "o.sheet.close": "Close",
})

export {}
