export { StatusBadge, type StatusKind } from "./status-badge"
export { StatCard, type StatTone } from "./stat-card"
export { SectionHeader } from "./section-header"
export { EmptyState } from "./empty-state"
export { AssumptionTag } from "./assumption-tag"
export { Term } from "./term"
// docs/ux-simplification.md §9.1 primitives
export { StoryBanner } from "./story-banner"
export { NextStep, AutoNextStep } from "./next-step"
export { Details } from "./details"
export { RunDemoButton } from "./run-demo-button"
export { BeforeAfterBar } from "./before-after-bar"
export { CreditEquation, fmtMoney2 } from "./credit-equation"
