// Typed access to /data/fixtures, generated from docs/api.md v0.1. Owner: Lane B.
// The fixtures themselves are generated by scripts/build_fixtures.py
// (`make fixtures`); never hand-edit them. Every file in data/fixtures is
// imported statically here, so a missing or renamed fixture fails `npm run build`.
//
// Type checking, in two layers:
// 1. Compile time: each import goes through `typed<T>()`, whose parameter is
//    `Widen<T>` (T with string-literal enums widened to string, tuples to arrays).
//    TypeScript infers JSON imports with plain `string`/`number[]`, so this is
//    the strictest structural check possible: a missing or mistyped key fails
//    the build. Nothing narrower than `string` can be checked this way.
// 2. Runtime: `checkFixtures()` checks every enum-typed field against the value
//    lists in ./types and that every file named in index.json is imported here.

import type {
  AssignmentsResponse,
  FixtureIndex,
  FundResponse,
  GapsResponse,
  HealthResponse,
  JobsResponse,
  LedgerResponse,
  PartsUploadResponse,
  ProgramResponse,
  ResetResponse,
  ResponseFor,
  RouteResponse,
  ShopDetailResponse,
  ShopsResponse,
} from "./types";
import {
  ASSIGNMENT_STATUSES,
  CERT_STATUSES,
  CERT_TYPES,
  CREDIT_CATEGORIES,
  FILTER_CODES,
  GAP_KINDS,
  JOB_STATUSES,
  MATERIALS,
  MULTIPLIERS,
  PACKAGE_STATUSES,
  PROCESS_TAGS,
  PROGRAM_STATES,
  RECIPIENT_TYPES,
  SHOP_LABELS,
  SHOP_SOURCES,
  SOLVERS,
  TAG_SOURCES,
  TOLERANCE_CLASSES,
  TRAINING_CATEGORIES,
  TXN_ORIGINS,
  TXN_TYPES,
} from "./types";

import indexJson from "@fixtures/index.json";
import healthJson from "@fixtures/health.json";
import demoResetJson from "@fixtures/demo_reset.json";
import programJson from "@fixtures/program.json";
import programAfterFundJson from "@fixtures/program_after_fund.json";
import partsUploadJson from "@fixtures/parts_upload.json";
import routeJson from "@fixtures/route.json";
import assignmentsJson from "@fixtures/assignments.json";
import assignmentsAfterFundJson from "@fixtures/assignments_after_fund.json";
import jobsJson from "@fixtures/jobs.json";
import jobsAfterFundJson from "@fixtures/jobs_after_fund.json";
import ledgerJson from "@fixtures/ledger.json";
import ledgerAfterFundJson from "@fixtures/ledger_after_fund.json";
import gapsJson from "@fixtures/gaps.json";
import gapsAfterFundJson from "@fixtures/gaps_after_fund.json";
import fundTP01Json from "@fixtures/fund_TP-01.json";
import fundTP02Json from "@fixtures/fund_TP-02.json";
import shopsJson from "@fixtures/shops.json";
import shopDemoJson from "@fixtures/shop_syn-012.json";
import shopDemoAfterFundJson from "@fixtures/shop_syn-012_after_fund.json";

// ---------------------------------------------------------------------------
// Compile-time structural check

/** T with every string-literal union widened to string, number literals to number, tuples to arrays. */
export type Widen<T> = T extends string
  ? string
  : T extends number
    ? number
    : T extends boolean
      ? boolean
      : T extends null | undefined
        ? T
        : T extends readonly (infer U)[]
          ? Widen<U>[]
          : T extends object
            ? { [K in keyof T]: Widen<T[K]> }
            : T;

/** Checks `value` against Widen<T> at compile time, then narrows it to T. */
function typed<T>(value: Widen<T>): T {
  return value as unknown as T;
}

// ---------------------------------------------------------------------------
// Typed exports

export const fixtures = {
  index: typed<FixtureIndex>(indexJson),
  health: typed<HealthResponse>(healthJson),
  reset: typed<ResetResponse>(demoResetJson),
  program: typed<ProgramResponse>(programJson),
  programAfterFund: typed<ProgramResponse>(programAfterFundJson),
  partsUpload: typed<PartsUploadResponse>(partsUploadJson),
  route: typed<RouteResponse>(routeJson),
  assignments: typed<AssignmentsResponse>(assignmentsJson),
  assignmentsAfterFund: typed<AssignmentsResponse>(assignmentsAfterFundJson),
  jobs: typed<JobsResponse>(jobsJson),
  jobsAfterFund: typed<JobsResponse>(jobsAfterFundJson),
  ledger: typed<LedgerResponse>(ledgerJson),
  ledgerAfterFund: typed<LedgerResponse>(ledgerAfterFundJson),
  gaps: typed<GapsResponse>(gapsJson),
  gapsAfterFund: typed<GapsResponse>(gapsAfterFundJson),
  fundTP01: typed<FundResponse>(fundTP01Json),
  fundTP02: typed<FundResponse>(fundTP02Json),
  shops: typed<ShopsResponse>(shopsJson),
  shopDemo: typed<ShopDetailResponse>(shopDemoJson),
  shopDemoAfterFund: typed<ShopDetailResponse>(shopDemoAfterFundJson),
} as const;

export type FixtureName = keyof typeof fixtures;

/** File name in data/fixtures → parsed contents. */
export const fixtureFiles: Readonly<Record<string, unknown>> = {
  "index.json": fixtures.index,
  "health.json": fixtures.health,
  "demo_reset.json": fixtures.reset,
  "program.json": fixtures.program,
  "program_after_fund.json": fixtures.programAfterFund,
  "parts_upload.json": fixtures.partsUpload,
  "route.json": fixtures.route,
  "assignments.json": fixtures.assignments,
  "assignments_after_fund.json": fixtures.assignmentsAfterFund,
  "jobs.json": fixtures.jobs,
  "jobs_after_fund.json": fixtures.jobsAfterFund,
  "ledger.json": fixtures.ledger,
  "ledger_after_fund.json": fixtures.ledgerAfterFund,
  "gaps.json": fixtures.gaps,
  "gaps_after_fund.json": fixtures.gapsAfterFund,
  "fund_TP-01.json": fixtures.fundTP01,
  "fund_TP-02.json": fixtures.fundTP02,
  "shops.json": fixtures.shops,
  "shop_syn-012.json": fixtures.shopDemo,
  "shop_syn-012_after_fund.json": fixtures.shopDemoAfterFund,
};

export const FIXTURE_COUNT = Object.keys(fixtureFiles).length;

export const demoIds = {
  programId: fixtures.index.program_id,
  shopId: fixtures.index.demo_shop_id,
  packageId: fixtures.index.demo_package_id,
} as const;

// ---------------------------------------------------------------------------
// Lookup through index.json

/**
 * Fixture for an endpoint, resolved through index.json, or null if none exists.
 * `path` is the concrete path ("/programs/northgate/ledger"); a query string is
 * ignored. With `afterFund`, the `after_fund` file is preferred and the routed
 * file is the fallback. Returns a deep copy, so callers may mutate it.
 */
export function getFixture<M extends string, P extends string>(
  method: M,
  path: P,
  opts?: { afterFund?: boolean },
): ResponseFor<Uppercase<M>, P> | null {
  const key = `${method.toUpperCase()} ${path.split("?")[0]}`;
  const { endpoints, after_fund } = fixtures.index;
  const file = (opts?.afterFund ? after_fund[key] : undefined) ?? endpoints[key];
  if (!file) return null;
  const data = fixtureFiles[file];
  if (data === undefined) return null;
  return structuredClone(data) as ResponseFor<Uppercase<M>, P>;
}

// ---------------------------------------------------------------------------
// Runtime contract check

type Allowed = readonly (string | number)[];

/** Keys whose values (or array items, or object keys for *_unlock / failing_filters) come from one closed set. */
const KEY_ENUMS: Record<string, Allowed> = {
  process_tags: PROCESS_TAGS,
  processes: PROCESS_TAGS,
  material: MATERIALS,
  materials: MATERIALS,
  tolerance_class: TOLERANCE_CLASSES,
  required_certs: CERT_TYPES,
  cert_unlock: CERT_TYPES,
  capacity_unlock: PROCESS_TAGS,
  failing_filters: FILTER_CODES,
  reason_code: FILTER_CODES,
  categories: TRAINING_CATEGORIES,
  recipient_type: RECIPIENT_TYPES,
  source: SHOP_SOURCES,
  shop_source: SHOP_SOURCES,
  tag_source: TAG_SOURCES,
  solver: SOLVERS,
  origin: TXN_ORIGINS,
  state: PROGRAM_STATES,
  kind: GAP_KINDS,
  multiplier: MULTIPLIERS,
};

function checkValue(allowed: Allowed, value: unknown, where: string, out: string[]): void {
  if (value === null) return;
  const items = Array.isArray(value)
    ? value
    : typeof value === "object"
      ? Object.keys(value as object)
      : [value];
  for (const v of items) {
    if (!allowed.includes(v as string | number)) out.push(`${where}: ${JSON.stringify(v)}`);
  }
}

function walk(node: unknown, where: string, out: string[]): void {
  if (Array.isArray(node)) {
    node.forEach((v, i) => walk(v, `${where}[${i}]`, out));
    return;
  }
  if (node === null || typeof node !== "object") return;
  for (const [k, v] of Object.entries(node)) {
    const allowed = KEY_ENUMS[k];
    if (allowed) checkValue(allowed, v, `${where}.${k}`, out);
    walk(v, `${where}.${k}`, out);
  }
}

/** Contract problems in the fixtures (empty when all is well). */
export function checkFixtures(): string[] {
  const out: string[] = [];
  const f = fixtures;
  const one = (allowed: Allowed, v: unknown, where: string) => checkValue(allowed, v, where, out);

  for (const [file, data] of Object.entries(fixtureFiles)) {
    if (file !== "index.json") walk(data, file, out);
  }
  const indexed = [...Object.values(f.index.endpoints), ...Object.values(f.index.after_fund)];
  for (const file of indexed) {
    if (!(file in fixtureFiles)) out.push(`index.json names ${file}, which fixtures.ts does not import`);
  }

  // Ambiguous keys (status, category, type, label), checked per object kind.
  one(["ok"], f.health.status, "health.json.status");
  for (const j of f.partsUpload.jobs) one(JOB_STATUSES, j.status, `parts_upload.json ${j.id}.status`);
  for (const j of f.jobs.jobs) one(JOB_STATUSES, j.status, `jobs.json ${j.id}.status`);
  for (const j of f.jobsAfterFund.jobs) one(JOB_STATUSES, j.status, `jobs_after_fund.json ${j.id}.status`);
  const assignments = [
    ...f.route.assignments,
    ...f.assignments.assignments,
    ...f.assignmentsAfterFund.assignments,
    ...f.fundTP01.unblocked_jobs,
    ...f.fundTP02.unblocked_jobs,
  ];
  for (const a of assignments) {
    one(ASSIGNMENT_STATUSES, a.status, `assignment ${a.job_id}.status`);
    one(["regular", "sme_direct"], a.category, `assignment ${a.job_id}.category`);
  }
  const txns = [
    ...f.ledger.transactions,
    ...f.ledgerAfterFund.transactions,
    f.fundTP01.training_txn,
    f.fundTP02.training_txn,
  ];
  for (const t of txns) {
    one(TXN_TYPES, t.type, `txn ${t.id}.type`);
    one(CREDIT_CATEGORIES, t.category, `txn ${t.id}.category`);
  }
  for (const ledger of [f.ledger, f.ledgerAfterFund]) {
    for (const row of ledger.multiplier_breakdown) one(CREDIT_CATEGORIES, row.category, "multiplier_breakdown.category");
  }
  const packages = [
    ...f.gaps.suggestions,
    ...f.gapsAfterFund.suggestions,
    f.fundTP01.package,
    f.fundTP02.package,
  ];
  for (const p of packages) {
    one(TRAINING_CATEGORIES, p.category, `package ${p.id}.category`);
    one(PACKAGE_STATUSES, p.status, `package ${p.id}.status`);
  }
  for (const s of f.shops.shops) {
    one(SHOP_LABELS, s.label, `shops.json ${s.id}.label`);
    for (const c of s.cert_summary) {
      one(CERT_TYPES, c.type, `shops.json ${s.id}.cert_summary.type`);
      one(CERT_STATUSES, c.status, `shops.json ${s.id}.cert_summary.status`);
    }
  }
  for (const detail of [f.shopDemo, f.shopDemoAfterFund]) {
    one(SHOP_LABELS, detail.shop.label, `shop ${detail.shop.id}.label`);
    for (const c of detail.certifications) {
      one(CERT_TYPES, c.type, `shop ${detail.shop.id} certification.type`);
      one(CERT_STATUSES, c.status, `shop ${detail.shop.id} certification.status`);
    }
    for (const o of detail.offers) one(ASSIGNMENT_STATUSES, o.status, `shop ${detail.shop.id} offer ${o.job_id}.status`);
    for (const t of detail.training) {
      one(PACKAGE_STATUSES, t.status, `shop ${detail.shop.id} training ${t.package_id}.status`);
      one(TRAINING_CATEGORIES, t.category, `shop ${detail.shop.id} training ${t.package_id}.category`);
    }
  }
  return out;
}
