// Wallet copy (T4). Registered with the shared t() dictionary so French can
// be dropped in later without touching the components.

import { extendStrings } from "@/lib/app/strings"

extendStrings("en", {
  "wallet.intro": "When each certificate lapses, the real deadline to act, and which jobs depend on it.",
  "wallet.summary.attention": "{count} need action",
  "wallet.summary.attention_one": "1 needs action",
  "wallet.summary.held": "{count} in place",
  "wallet.summary.held_one": "1 in place",
  "wallet.summary.training": "{count} in training",
  "wallet.summary.training_one": "1 in training",
  "wallet.summary.notHeld": "{count} not held",
  "wallet.summary.notHeld_one": "1 not held",
  "wallet.summary.clear": "Nothing needs action",
  "wallet.notRouted": "Jobs at risk appear once Northgate matches its parts list to shops.",
  "wallet.notHeldSection": "Not held",
  "wallet.notHeldBody": "Shieldworks has no record of this certificate.",
  "wallet.notHeldUnlocks": "Can unlock more jobs · see Grow",
  "wallet.notHeldNoUnlock": "On its own, it won't open any of Northgate's current jobs.",
  "wallet.loadError": "Could not load certificates",
  "wallet.retry": "Try again",

  "wallet.days.left": "days to act",
  "wallet.days.left_one": "day to act",
  "wallet.days.overdue": "days past act-by",
  "wallet.days.overdue_one": "day past act-by",
  "wallet.days.lapsed": "days since it lapsed",
  "wallet.days.lapsed_one": "day since it lapsed",
  "wallet.days.none": "No date",

  "wallet.row.expand": "Show details for {cert}",
  "wallet.row.expires": "Expires",
  "wallet.row.actBy": "Act by",
  "wallet.row.windowOpens": "Reminder window opens",
  "wallet.row.processing": "Processing: up to {days} business days",
  "wallet.row.rule": "Official rule",
  "wallet.row.source": "Source: {label}",
  "wallet.row.moreSources": "Also: {label}",
  "wallet.row.atRisk": "At risk if it lapses:",
  "wallet.row.atRiskNone": "No matched jobs depend on it right now.",
  "wallet.row.neededFor": "Needed for",
  "wallet.row.neededForNone": "No offered jobs are waiting on it right now.",
  "wallet.row.startsWhenQualified": "starts when welders qualify",
  "wallet.row.startsWhenTrained": "starts when training is done",
  "wallet.row.trainingBody": "Welders are in training, paid by Northgate. It counts as held once they qualify.",
  "wallet.row.trainingBodyGeneric": "Training is under way, paid by Northgate. It counts as held once it's done.",
  "wallet.row.declaredExpiry": "Expiry you entered: {date}",
  "wallet.row.atRiskNotRouted": "Work at risk shows once Northgate matches its parts list to shops.",
  "wallet.row.consequence": "If it lapses",
  "wallet.row.registry": "Check the {label}",
  "wallet.row.wallCert": "A wall certificate alone isn't proof; primes check the registry.",
  "wallet.row.noRegistry": "No public registry. This is always shop-declared.",
  "wallet.row.declared": "shop-declared · not yet used for matching",
  "wallet.row.declaredOn": "You added this date on {date}",
  "wallet.row.certNumber": "Certificate no. {number}",
  "wallet.row.illustrative": "Synthetic shop: this date is illustrative.",
  "wallet.row.addExpiry": "Add expiry date",
  "wallet.row.editExpiry": "Change expiry date",
  "wallet.row.seeWhatItTakes": "See what it takes",
  "wallet.row.notHeld": "Not held",
  "wallet.row.noDate": "Shieldworks has no expiry date for this.",
  "wallet.row.actByAssumption": "Act-by offset is an assumption, not an official deadline",
  "wallet.row.remindAssumption": "Reminder window length is an assumption",
  "wallet.row.ruleAssumption": "This cycle length is an assumption",
  "wallet.row.inferred": "Part of this rule is inferred",
  "wallet.row.willSend": "Will send",

  "wallet.bar.label": "{cert}: today is {today}. Act by {actBy}. Expires {expires}.",
  "wallet.bar.today": "Today",
  "wallet.bar.window": "Reminder window",
  "wallet.bar.urgent": "Last 30 days before act-by",
  "wallet.bar.late": "Past act-by",

  "wallet.sheet.title": "Expiry date: {cert}",
  "wallet.sheet.body": "Enter the expiry date printed on your certificate. It shows as shop-declared, never verified, and Shieldworks won't use it for matching until reviewed.",
  "wallet.sheet.date": "Expiry date",
  "wallet.sheet.number": "Certificate number (optional)",
  "wallet.sheet.numberHint": "Up to 40 characters",
  "wallet.sheet.save": "Save date",
  "wallet.sheet.saving": "Saving…",
  "wallet.sheet.cancel": "Cancel",
  "wallet.sheet.noDrawings": "Certificates only. Never upload or photograph drawings or technical data.",
  "wallet.sheet.saved": "Expiry date saved: {cert}",
  "wallet.sheet.savedBody": "Shop-declared · not yet used for matching",
  "wallet.sheet.pickDate": "Pick a date",
})
